# Site settings
title: "Victor's Blog"
tagline: "A random software engineer's blog. Enjoy it!"
sidebar_image: /images/cover.jpg

# Build settings
# markdown: redcarpet
highlighter: rouge
baseurl: /blog

# RSS
name:         Victor's Blog
description:  A random software engineer's blog.
url:          https://victor-ds.github.io/blog/